blog_multiauthor/blogApp/urls.py
from django.urls import path
from .views import *

app_name = 'blogApp'
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path("postarPublicacao", PostCreateView.as_view(), name="postar"),
    path('listarPubliacoes', PostListView.as_view(), name="listar"),
    path('accounts/profile', testeAutenticacao.as_view(), name='loginPersonalizado')
]

blog_multiauthor/blog_multiauthor/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from blogApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blogApp.urls')),
     path('accounts/', include('allauth.urls')), 
      path('accounts/profile', views.testeAutenticacao.as_view(), name='loginPersonalizado')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_multiauthor/blogApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django_summernote.fields import SummernoteTextField # type: ignore




# Create your models here.


class Post(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('approved', 'Approved'),
    ]

    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(default="Um teste de conteudo")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True) # soft delete
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending') # aprovação para moderadores
    def __str__(self):
        return self.title

blog_multiauthor/blogApp/forms.py
from django import forms
from .models import Post
from django_summernote.widgets import SummernoteWidget
from django_summernote.widgets import SummernoteInplaceWidget

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'author', 'content', 'status', 'active']
        widgets = {
             'content': SummernoteWidget(),
        }

blog_multiauthor/blogApp/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView
from django.urls import reverse_lazy
from .models import Post
from .forms import PostForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from django.http import JsonResponse
from django.views.decorators.clickjacking import xframe_options_exempt
from django.utils.decorators import method_decorator
# Create your views here.

class HomeView(TemplateView):
    template_name = 'blogApp/home.html'

@method_decorator(xframe_options_exempt, name='dispatch')
class PostCreateView(CreateView , LoginRequiredMixin):
    model = Post
    form_class = PostForm  # Se você estiver usando um formulário personalizado
    template_name = 'blogApp/createPost.html'
    success_url = reverse_lazy('blogApp:home') 
    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data 
    def post(self, request, *args, **kwargs):
        # Imprime os campos recebidos para depuração
        

        # Chama o método post original para processar o formulário
        content = request.POST.get('content', '')
        
        # Marcar como seguro para armazenar HTML no banco
        content_tratado= content.replace('"', "'")

        print("cleaned_tratado: abaixo")
        print(content_tratado)

        # Atualiza o POST para incluir o conteúdo tratado
        request.POST = request.POST.copy()
        request.POST['content'] = content_tratado

        
        # Chama o método post original
        return super().post(request, *args, **kwargs)

        # Retorna uma resposta JSON como exemplo
        if request.is_ajax():
            return JsonResponse({"message": "Dados recebidos com sucesso!"})
        return response


class PostListView(ListView):
    model = Post
    paginate_by = 10
    context_object_name = 'posts'
    template_name = 'blogApp/listPosts.html'

from allauth.socialaccount.adapter import get_adapter

class testeAutenticacao(TemplateView):
    template_name = 'blogApp/testeAutenticacao.html'
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     adapter = get_adapter(self.request)
    #     context['social_providers'] = adapter.list_providers(self.request)
    #     print(str(context))
    #     return context

blog_multiauthor/blogApp/templates/blogApp/createPost.html
{% extends "core/base.html" %}

{% block title %}Página Inicial{% endblock %}

{% block content %}
   
<h1>Formulário de criação de Post</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}  <!-- Exibe o formulário como parágrafos -->
    
    <button type="submit">Criar Post</button>
  </form>
  {% load socialaccount %}


<a href="{% provider_login_url "google" process="connect" %}">Connect a Google account</a>
{% endblock %}

blog_multiauthor/blogApp/templates/blogApp/home.html
{% extends "core/base.html" %}

{% block title %}Página Inicial{% endblock %}

{% block content %}
    
<h1>Página home inicial</h1>
{% endblock %}

blog_multiauthor/blogApp/templates/blogApp/listPosts.html
{% extends "core/base.html" %}

{% block title %}Página Inicial{% endblock %}

{% block content %}
<h1>Aqui a listagem de posts</h1>
<ul>
    {% for post in posts %}
        <li>{{ post.title }}</li>
        {{post.content|safe}}
        {{post.contentTextTest|safe}}
        <!-- <div id="content"></div> -->
        <script defer>
            // document.getElementById("content").innerHTML = "{{ post.contentTextTest|escapejs }}";

        </script>
    {% endfor %}
</ul>
{% endblock %}

blog_multiauthor/blogApp/templates/blogApp/testeAutenticacao.html
<h2>Login via Redes Sociais</h2>
<ul>
    {% for provider in social_providers %}
        <li>
            <a href="{{ provider.login_url }}">{{ provider.name }}</a>
        </li>
    {% endfor %}
    <a href="{% url 'account_logout'%}">Logout</a>
</ul>

blog_multiauthor/blogApp/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Meu Site{% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="{% static 'blogApp/core/css/style.css' %}" />
  </head>
  <body>
    {% if user.is_authenticated %}
    <header class="p-3 mb-3 border-bottom header-authenticated">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none">
            <img src="./media/blogApp/basehtml/images.png" alt="uma imagem" width="80" height="80" />
          </a>

          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'blogApp:home' %}" class="nav-link px-2 link-secondary">Inicio</a></li>
            <li><a href="{% url 'blogApp:postar' %}" class="nav-link px-2 link-body-emphasis">Criar Post</a></li>
            <li><a href="{% url 'blogApp:listar' %}" class="nav-link px-2 link-body-emphasis">Listar Post</a></li>
            <li><a href="#" class="nav-link px-2 link-body-emphasis">Outra coisa</a></li>
          </ul>

          <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
            <input type="search" class="form-control" placeholder="Search..." aria-label="Search" />
          </form>

          <div class="dropdown text-end">
            <a
              href="#"
              class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle" />
            </a>
            <ul class="dropdown-menu text-small">
              <li><a class="dropdown-item" href="#">New project...</a></li>
              <li><a class="dropdown-item" href="#">Settings</a></li>
              <li><a class="dropdown-item" href="#">Profile</a></li>
              <li><hr class="dropdown-divider" /></li>
              <li><a class="dropdown-item" href="#">Sign out</a></li>
            </ul>
          </div>
        </div>
      </div>
    </header>

    <header class="p-3 mb-3 border-bottom header-authenticated-mobile">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <div class="d-flex w-100 align-items-center justify-content-between mb-3 mt-2">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none">
              <img src="./media/blogApp/basehtml/images.png" alt="uma imagem" width="80" height="80" />
            </a>

            <div class="d-flex gap-3 align-items-center">
              <i class="bi bi-list" id="icon-menu"></i>
              <div class="dropdown text-end">
                <a
                  href="#"
                  class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle" />
                </a>
                <ul class="dropdown-menu text-small">
                  <li><a class="dropdown-item" href="#">New project...</a></li>
                  <li><a class="dropdown-item" href="#">Settings</a></li>
                  <li><a class="dropdown-item" href="#">Profile</a></li>
                  <li><hr class="dropdown-divider" /></li>
                  <li><a class="dropdown-item" href="#">Sign out</a></li>
                </ul>
              </div>
            </div>
          </div>

          <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
            <input type="search" class="form-control" placeholder="Search..." aria-label="Search" />
          </form>
        </div>
      </div>
    </header>
    {% else %}
    <header class="p-3 mb-3 border-bottom header-isnot-authenticated">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none">
            <img src="./media/blogApp/basehtml/images.png" alt="uma imagem" width="80" height="80" />
          </a>

          <ul class="nav col-6 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'blogApp:home' %}" class="nav-link px-2 link-secondary">Inicio</a></li>
            <li><a href="{% url 'blogApp:postar' %}" class="nav-link px-2 link-body-emphasis">Criar Post</a></li>
            <li><a href="{% url 'blogApp:listar' %}" class="nav-link px-2 link-body-emphasis">Listar Post</a></li>
            <li><a href="#" class="nav-link px-2 link-body-emphasis">Outra coisa</a></li>
          </ul>

          <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
            <input type="search" class="form-control" placeholder="Search..." aria-label="Search" />
          </form>

          <div class="col-md-3 col-lg-auto">
            <button type="button" class="btn btn-outline-primary me-2">Login</button>
            <button type="button" class="btn btn-primary">Sign-up</button>
          </div>
        </div>
      </div>
    </header>

    <!-- mobile not authenticated  ---------------------------------------------------------------------->

    <header class="p-3 mb-3 border-bottom header-isnot-authenticated-mobile">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <div class="d-flex align-items-center justify-content-between w-100 mb-3">
            <a href="/">
              <img src="./media/blogApp/basehtml/images.png" alt="uma imagem" width="80" height="80" />
            </a>

            <i class="bi bi-list" id="icon-menu"></i>
          </div>

          <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
            <input type="search" class="form-control" placeholder="Search..." aria-label="Search" />
          </form>

          <div class="col-md-3 col-lg-auto">
            <button type="button" class="btn btn-outline-primary me-2">Login</button>
            <button type="button" class="btn btn-primary">Sign-up</button>
          </div>
        </div>
      </div>
    </header>
    {% endif %}

    <main>{% block content %}{% endblock %}</main>
    <footer class="padding-top: 1rem">
      <ul class="nav justify-content-center py-3">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
      </ul>
      <hr style="width: 30%; margin: 0 auto; padding-bottom: 1.2rem" />
      <p class="text-center text-body-secondary">&copy; 2024 Company, Inc</p>
    </footer>

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
      integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>